npx expo install expo-apple-authentication@~5.0.1
npx expo install expo-asset@~8.7.0
npx expo install expo-build-properties@~0.4.1
npx expo install expo-checkbox@~2.2.2
npx expo install expo-constants@~14.0.2
npx expo install expo-dev-client@~2.0.1
npx expo install expo-device@~5.0.0
npx expo install expo-firebase-analytics@~8.0.0
npx expo install expo-firebase-core@~6.0.0
npx expo install expo-font@~11.0.1
npx expo install expo-image-picker@~14.0.2
npx expo install expo-linear-gradient@~12.0.1
npx expo install expo-linking@~3.3.1
npx expo install expo-notifications@~0.17.0
npx expo install expo-splash-screen@~0.17.5
npx expo install expo-status-bar@~1.4.2
npx expo install expo-system-ui@~2.0.1
npx expo install expo-updates@~0.15.6
npx expo install expo-web-browser@~12.0.0
npx expo install react@18.1.0
npx expo install react-dom@18.1.0
npx expo install react-native@0.70.8
npx expo install react-native-gesture-handler@~2.9.0
npx expo install react-native-safe-area-context@4.4.1
npx expo install react-native-screens@~3.18.0
npx expo install react-native-svg@13.4.0
npx expo install react-native-web@~0.18.9
